"""Add stadium back to teams

Revision ID: 9f55e7025f8d
Revises: fd0e9485a1a4
Create Date: 2026-08-27 15:22:37.121411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f55e7025f8d'
down_revision: Union[str, Sequence[str], None] = 'fd0e9485a1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('stadium', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'stadium')
    # ### end Alembic commands ###
